<?php
/**
 * User: wangzd
 * Email: wangzhoudong@liwejia.com
 * Date: 2017/5/15
 * Time: 15:08
 */
namespace Yijipay\Transfer;

class Config {
    static $bank = [
        'BANKSH'=>'上海银行',
        'PINGANBANK'=>'平安银行',
        'SDB'=>'深圳发展银行',
        'ICBC'=>'工商银行',
        'ABC'=>'农业银行',
        'BOC'=>'中国银行',
        'CCB'=>'建设银行',
        'COMM'=>'交通银行',
        'CMB'=>'招商银行',
        'CITIC'=>'中信银行',
        'CEB'=>'光大银行',
        'CIB'=>'兴业银行',
        'CMBC'=>'民生银行',
        'HXB'=>'华夏银行',
        'SPDB'=>'浦发银行',
        'PSBC'=>'邮政储蓄银行',
        'PINGANBK'=>'平安银行',
        'BKSH'=>'上海银行',
        'BOBJ'=>'北京银行',
        'CQTGB'=>'重庆三峡银行',
        'CGB'=>'广发银行',
        'GZCB'=>'广州银行',
        'HSBC'=>'汇丰银行',
        'KMCB'=>'富滇银行',
        'CQRCB'=>'重庆农村商业银行',
        'CDRCB'=>'成都农村商业银行',
        'SHRCB'=>'上海农村商业银行',
        'BJRCB'=>'北京农村商业银行',
        'TJRCB'=>'天津农村商业银行',
        'SZRCB'=>'深圳农村商业银行',
        'GZRCB'=>'广州农村商业银行',
        'GYCB'=>'贵阳市商业银行',
        'HBCB'=>'哈尔滨银行',
        'WHCB'=>'汉口银行',
        'EBCL'=>'恒丰银行',
        'JLCB'=>'吉林银行',
        'TZBK'=>'台州银行',
        'HZCB'=>'杭州银行',
        'XMCB'=>'厦门银行',
        'LUOYBK'=>'洛阳市商业银行',
        'ZHESHANGB'=>'浙商银行',
        'CQCB'=>'重庆银行',
        'BOCD'=>'成都银行',
        'CBHB'=>'渤海银行',
        'DLCB'=>'大连银行',
        'NJCB'=>'南京银行',
        'TJCB'=>'天津银行',
        'HSB'=>'徽商银行',
        'BTCB'=>'包商银行',
        'BONX'=>'宁夏银行',
        'NBCB'=>'宁波银行',
        'NCCB'=>'宁波通商银行',
        'BOGZ'=>'贵州银行',
        'UNION'=>'银联',
        'BEA'=>'东亚银行',
        'ZJCBANK'=>'广东南粤银行',
        'CFCA'=>'中国金融认证中心',
        'LZBANK'=>'兰州银行',
        'SCRCU'=>'四川农信',
        'DRCBANK'=>'东莞农商',
        'GDRCU'=>'广东农信',
        'HAINANBANK'=>'海南农信',
        'HBXH'=>'湖北农信',
        'JXNXS'=>'江西农信',
        'QZCB'=>'泉州银行',
        'JSRCU'=>'江苏省农村信用社联合社',
        'ALIPAY'=>'支付宝',
        'APPLEPAY'=>'ApplePay',
        'WEBANK'=>'深圳前海微众银行股份有限公司',
    ];
}